[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn basehook.api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/webhooks"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
